### ISSUE TITLE
Points to be added to the recommended practices list

### ISSUE THREAD

**Issue by tobyhodges** [common-workflow-language/user_guide#15]
- subworkflow refactoring and levels of abstraction - example wording (from @MarkRobbo [here](https://github.com/common-workflow-language/cwlviewer/pull/120/commits/fccfb53210f159941ce0550ce2db2dbb9c1e0584)):
> CWL implementations which also implement <code>SubworkflowFeatureRequirement</code> can support nesting workflows as a step within others. Complex workflows with individual components which can be abstracted should utilise this to make their workflow modular and allow sections of them to be easily reused

**Comment by tobyhodges** [comment]
accidentally merged this ( #40 ) without chance for review. Please take a look and let me know if you want me to revert/revise.

**Comment by mr-c** [comment]
All good, thanks!
