### ISSUE TITLE
Document the build process

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/user_guide#157]
See https://github.com/common-workflow-language/user_guide/issues/148#issuecomment-516719860

https://carpentries.github.io/lesson-example/
https://carpentries.github.io/curriculum-development/technological-introductions.html

Explain the changes we made for this user guide
- `carpentry` is `cwl`
- others?

**Comment by tobyhodges** [comment]
I'll try to take a look at this over the next week or two.
