### ISSUE TITLE
Example for using expressions with exclusive parameters

### ISSUE THREAD

**Issue by pvanheus** [common-workflow-language/user_guide#162]
If you use exclusive parameters (as documented in the [Advanced Parameters](https://www.commonwl.org/user_guide/11-records/index.html)) section together with expressions you might end up with a situation where an expression is undefined. An example of such non-working CWL is [here](https://gist.github.com/pvanheus/f6bdc3ead51eacbee7b6d59398d41f39).

The solution is to use logical OR to provide a default value to the expression (thanks to @tetron) for explaining this. I.e. expressions like `$(inputs.output.output_file || [])`. This works because expressions are [ECMAScript expressions](https://www.commonwl.org/v1.0/CommandLineTool.html#Expressions), something I didn't realise until last night.

I am preparing a pull request to add this explanation to the User Guide but I cannot right now come up with a simple example illustrating this, so I'm opening this issue to ask if anyone can come up with a straightforward example and also to remind myself to complete this addition to the guide.

**Comment by kinow** [comment]
Link to new Advanced Inputs section, which has the same contents as the old Advanced Parameters linked above: https://www.commonwl.org/user_guide/topics/inputs.html#advanced-inputs
