### ISSUE TITLE
Goals

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/user_guide#2]
- [x] migrate the current user guide to a more friendly editing format
- [ ] make the material modular and suitable for both use in Carpentry style workshops and self paced learning
- [ ] generate all output sections using the reference implementation and test outputs using the specified and latest releases of `cwltool`
- [ ] make material remix friendly, especially for customization of examples to be more specific for a targeted group
- [ ] make material translation friendly (modular, and.. ?). Figure out how to deliver the correct language. Maybe use ReadTheDocs for this?

**Comment by tobyhodges** [comment]
ok, thanks. For now, I will concentrate only on the first point here.

**Comment by mr-c** [comment]
@tobyhodges Your assistance is greatly appreciated!

**Comment by mr-c** [comment]
@tobyhodges Okay. I've run the `bin/lesson_initialize.py` and I'll finish customizing it before making a PR
