### ISSUE TITLE
Examples of Operations

### ISSUE THREAD

**Issue by RenskeW** [common-workflow-language/user_guide#218]
Hello everyone,

I'm quite new to CWL and would like to add Operations to my workflows since not all the steps are defined as CWL CommandLineTools yet. However, in the CWL [user guide](https://www.commonwl.org/user_guide/) I cannot find an explanation of how to implement these and the [documentation](https://www.commonwl.org/v1.2/Workflow.html#Operation) does not give examples either. 

Is it possible to add a simple example workflow to the user guide in which some of the steps are Operations? 

Many thanks,

Renske

**Comment by mr-c** [comment]
Here is one example: https://github.com/workflowhub-eu/galaxy2cwl/raw/42469c0a384e62a90e6828b2e429ccac3c97c414/examples/covid19/genomics/Galaxy-Workflow-COVID-19__Assembly.cwl

see also https://github.com/common-workflow-language/cwl-v1.2/pull/3
