### ISSUE TITLE
Add TypeScript to the user guide

### ISSUE THREAD

**Issue by kinow** [common-workflow-language/user_guide#227]
Follow-up for discussion from #222 

https://github.com/common-workflow-language/user_guide/issues/222#issuecomment-1188987658

We just need to define the public, how we will present, if we will list any pros & cons, if there are improvements necessary to be used by any user or if there are known issues, links to code repository, presentations, etc.

Also need to think where this could go. It could go into tutorials, how-tos, a dedicated section, maybe subsection of the expressions section, etc.

**Comment by mr-c** [comment]
This is cool, but also very advanced. Should definitely be in its own section, with lots of warnings. I have real concerns about the human portability of such an approach.

Maybe the cwl-patterns repo is a better place to document this approach? https://github.com/common-workflow-library/cwl-patterns

**Comment by alexiswl** [comment]
Yep, would definitely put this under an advanced topic but I think with good documentation concerns can be mitigated. I also agree that cwl-patterns is probably a good repo for this, since this is more of a conceptual best practise rather than a how-to.

This CWL Patterns could also be show-cased more, I didn't know it existed until now (since it's under a different GitHub org). If we put this in the CWL patterns is there a way that we can link it in the user guide?

**Comment by tetron** [comment]
@alexiswl 

There's an experimental cwltool feature that you might be interested in, it is exactly designed to formalize the concept of having a pre-process step to produce the code that will actually be executed, in this case compiling typescript to javascript:

https://github.com/common-workflow-language/cwltool/blob/main/docs/processgen.rst

**Comment by mr-c** [comment]
> This CWL Patterns could also be show-cased more, I didn't know it existed until now (since it's under a different GitHub org). If we put this in the CWL patterns is there a way that we can link it in the user guide?

I agree that it could be made more prominent. Currently the cwl patterns repo is listed without context or motivation as item 4 under "You also may be interested in:" on https://www.commonwl.org/user_guide/ (but "below the fold" of the first screen)

**Comment by alexiswl** [comment]
> @alexiswl

> There's an experimental cwltool feature that you might be interested in, it is exactly designed to formalize the concept of having a pre-process step to produce the code that will actually be executed, in this case compiling typescript to javascript:

> [common-workflow-language/cwltool@main/docs/processgen.rst](https://github.com/common-workflow-language/cwltool/blob/main/docs/processgen.rst?rgh-link-date=2022-07-22T16%3A22%3A31Z)

Thanks for this, wasn't aware of this concept. 

To confirm, this process (typescript to javascript via tsc) would run at the start of every invocation? And is dependent on the workflow engine knowing how to correctly implement and use the ProcessGenerator extension?
