### ISSUE TITLE
mystery checkbox in side-bar

### ISSUE THREAD

**Issue by manabuishii** [common-workflow-language/user_guide#244]
Hello .
I'm Manabu Ishii.

Thanks nice user guide !!

Question .
There is a checkbox at left pain "Topics" . ( Red circle)
How can I use it ?
In my Mac Chrome browser ,  nothing happens at least my environment.

Suggestion .
I think center pain move to left . ( Blue arrow )
At least my browser there is some spaces , so first time I can not find left pain menu.

<img width="1047" alt="スクリーンショット 2022-09-02 10 37 14" src="https://user-images.githubusercontent.com/7508005/188041464-38c4a55f-4c53-41f7-80d1-632de49d846f.png">

**Comment by kinow** [comment]
Hi @manabuishii ! :wave: 

Good catch, I noticed something similar: https://github.com/common-workflow-language/user_guide/commit/0604c7a13ef0eb4968cceda0880f21a934b87154#commitcomment-82739272

**Comment by Fienne** [comment]
I think what we should do is remove the sidebar from the right side of the introduction and topics pages OR add the sidebar to the Tutorials, FAQ and Licenses pages, so that the design on all pages look consistent.  
 How does this sound @kinow ?

**Comment by kinow** [comment]
My preference is to have the same layout in every page. The landing page of the user guide, IMO, is no different than the rest of the guide. So having a consistent layout prevents users from having to treat pages in any different way (i.e. on this page you have a sidebar, on this one you don't... on this page your search is here, on that page it is not...).

**Comment by Fienne** [comment]
So what we should do is add the sidebar to the pages that don't have it?

**Comment by kinow** [comment]
> So what we should do is add the sidebar to the pages that don't have it?

Not sure, that was just my opinion :slightly_smiling_face: One issue here is that check box that appears on the desktop view (I think it's not shown on mobile?). I would start investigating if this change can be reverted or if there is a setting or dependency somewhere that needs changing: https://github.com/common-workflow-language/user_guide/commit/0604c7a13ef0eb4968cceda0880f21a934b87154#commitcomment-82739272

**Comment by Fienne** [comment]
No, it's not shown on mobile. I don't really know the function of the checkbox. What does it do?

**Comment by kinow** [comment]
> No, it's not shown on mobile. I don't really know the function of the checkbox. What does it do?

I think it doesn't do anything. I suspect it is rendered by accident as the function used in the commit was either not supposed to be used at that part of the template, or because the template requires some setting for that function to work correctly. But that requires some investigation to confirm it :+1: 

But no functional feature. We could even try to simply hide it in CSS if needed, but I think it would be better to understand why it was added and what's the correct fix.

**Comment by Fienne** [comment]
I'll try finding out the file which renders it and understand why it was added. If you're able to figure it out before I do, please share.

**Comment by kinow** [comment]
Excellent @Fienne . I probanly won't work on it (busy with $work and a few other tasks). Good luck!

**Comment by Mackenzie-OO7** [comment]
> I'll try finding out the file which renders it and understand why it was added. If you're able to figure it out before I do, please share.

Hey, did you figure this out yet?
