### ISSUE TITLE
Navigating the User Guide Mentions Core Concepts Section but it doesn't exist

### ISSUE THREAD

**Issue by swzCuroverse** [common-workflow-language/user_guide#255]
Navigating the User Guide
If you are a beginner user get started with the [Introduction](https://www.commonwl.org/user_guide/introduction/index.html) section. For advanced users the subsections of the [Core Concepts](https://www.commonwl.org/user_guide/topics/index.html) have detailed information about the most common topics for CWL.

Perhaps we can just called it the Topics section since there is on Core Concepts -- or if we like Core Concepts change the name of the Topics Section?

**Comment by kinow** [comment]
I think that might be due to some rework, as we used to have initial concepts and core concepts.

**Comment by swzCuroverse** [comment]
Ok - so this bug fix will just be changing Core Concepts to Topics :)

**Comment by Fienne** [comment]
@swzCuroverse  I think this issue has been fixed because I can't find the "Core Concepts" heading on the page anymore. I can see just "Topics" [here](https://www.commonwl.org/user_guide/topics/index.html)
