### ISSUE TITLE
user guide doc typos

### ISSUE THREAD

**Issue by Fienne** [common-workflow-language/user_guide#286]
The user guide website has typos on some pages. it'll be nice if we were able to identify these typos which have to be corrected.
This issue contains any document typos found on the user guide website. You can add the identified typos using the format below. The typos are categorized by their web pages.  
**Check to be sure that an entry doesn't already exist.**  

- [ ] Home page - https://www.commonwl.org/user_guide/
  - [ ] Bioinformatics -> Bio informatics, Bio-informatics

- [x] Topics page - https://www.commonwl.org/user_guide/topics/yaml-guide.html
  - [x] scientfic -> scientific

#
Each word could have a suggestion(or suggestions) which is pointed to by an arrow. Possible tools that can be used to check for typos are: 

- https://www.w3.org/2002/01/spellchecker
- [Internet Marketing Ninja](https://www.internetmarketingninjas.com/online-spell-checker.php)
- [Website Grammar and Spell Check](https://www.grammar.com/check-website.php)

**Comment by Pep7799** [comment]
Hello @Fienne. 
I noticed that in the "Navigating the User Guide" on the home page, the last sentence there, we have the "Search form is on the left sidebar", but from my end I can see it on the right top menu

**Comment by Mackenzie-OO7** [comment]
- [ ] FAQ page - https://www.commonwl.org/user_guide/faq.html
- [ ] commandline -> command-line, command line

**Comment by Fienne** [comment]
> Hello @Fienne. I noticed that in the "Navigating the User Guide" on the home page, the last sentence there, we have the "Search form is on the left sidebar", but from my end I can see it on the right top menu

Mine is on the right top menu too. I think it may be a styling issue

**Comment by mr-c** [comment]
These are fixed; thanks!
