### ISSUE TITLE
Zenodo not updating

### ISSUE THREAD

**Issue by swzCuroverse** [common-workflow-language/user_guide#308]
@mr-c said Zenodo would auto-update.  However when I look at the Zenodo page - the last release is listed as in 2017. So, is there something we have to do to update the Zenodo?

**Comment by kinow** [comment]
Could be something with the integration github ←→ zenodo too, e.g. https://github.com/zenodo/zenodo/issues/2243

Someone with access to the settings could try what one comment mentions about hooks, or maybe someone with access to zenodo. Maybe there's some info like in RTD.

**Comment by mr-c** [comment]
Yeah, I saw this didn't work.

Thanks for the hint @kinow ; https://zenodo.org/account/settings/github/repository/common-workflow-language/user_guide shows

```
{
    "errors": "{'metadata': {'creators': {3: {'orcid': ['Not a valid ORCID identifier.']}}}}"
}
```

I fixed this in https://github.com/common-workflow-language/user_guide/commit/09030ed6d2d94e0dc91a4d672effaf904c8c2936

**Comment by mr-c** [comment]
That worked, the new release is at https://zenodo.org/record/7220770

**Comment by kinow** [comment]
Thanks for fixing it so quickly @mr-c, and thanks for reporting this @swzCuroverse !
