### ISSUE TITLE
Add images and links to the contributing doc to help users setup the project

### ISSUE THREAD

**Issue by MARVEBUKA** [common-workflow-language/user_guide#321]
[contributing with GitHub web](https://github.com/common-workflow-language/user_guide/blob/e24e362a8662314cca337c1ff7ac28401df899c4/CONTRIBUTING.md#using-github) has very useful information.

I was thinking adding some sample images to show the actions would be helpful for some "first time contributors". Also maybe links to the repo to be forked could help reduce confusion on which repo to fork.

**Comment by swzCuroverse** [comment]
We are pretty specific about moving to main branch and it is on the repo, so I am not sure where a link would help.  If you have a specific place, you can let me know.  

So I believe the best way to approach this is to link out to GitHub or git tutorials as much as possible and just have things specific to the User Guide repo be put in the contribution guide.  This is for several reasons but mainly (1) GitHub resources probably are better maintained and more up to date than anything we write ourselves and (2) If we copy over content than we will be responsible for resync-ing everytime anything changes in the GitHub UI.  So, I would prefer to link out to resources if at all possible. 

 I believe we already have the links here "If you choose to contribute via GitHub, you may want to look at [How to Contribute to an Open Source Project on GitHub](https://docs.github.com/en/get-started/quickstart/contributing-to-projects). To manage changes, we follow [GitHub flow](https://guides.github.com/introduction/flow/). To use the web interface for contributing:"   --> 

but if you have additional links you think are useful you can add to that section.

**Comment by MARVEBUKA** [comment]
> We are pretty specific about moving to main branch and it is on the repo, so I am not sure where a link would help. If you have a specific place, you can let me know.
> 
> So I believe the best way to approach this is to link out to GitHub or git tutorials as much as possible and just have things specific to the User Guide repo be put in the contribution guide. This is for several reasons but mainly (1) GitHub resources probably are better maintained and more up to date than anything we write ourselves and (2) If we copy over content than we will be responsible for resync-ing everytime anything changes in the GitHub UI. So, I would prefer to link out to resources if at all possible.
> 
> I believe we already have the links here "If you choose to contribute via GitHub, you may want to look at [How to Contribute to an Open Source Project on GitHub](https://docs.github.com/en/get-started/quickstart/contributing-to-projects). To manage changes, we follow [GitHub flow](https://guides.github.com/introduction/flow/). To use the web interface for contributing:" -->
> 
> but if you have additional links you think are useful you can add to that section.

Well understood @swzCuroverse thank you. I'll close the issue now.
