### ISSUE TITLE
LHS Navigation is collapsed strangely and hard to read

### ISSUE THREAD

**Issue by swzCuroverse** [common-workflow-language/user_guide#351]
I am not sure when this happened but it seems to be broken now at least on my Linux machine running Firefox and Chrome. 
![Screenshot from 2022-12-12 16-26-51](https://user-images.githubusercontent.com/15944983/207158416-44099b09-95eb-456f-90ef-10cc1688a0e7.png)

@kinow any ideas?

**Comment by swzCuroverse** [comment]
It is is OK on release, so it looks like it was something pull directly to release without being in main?

**Comment by kinow** [comment]
It's fixed already, just not released I think. Let me find the issues to link here.

**Comment by swzCuroverse** [comment]
Oh great.  Let's see if we can get that out huh :)

**Comment by swzCuroverse** [comment]
@kinow I am going to close this out, if I can.
