### ISSUE TITLE
Finish requeste Libre hosting @ Weblate

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/user_guide#362]
- [ ] Define translation instructions to give translators a guideline. (can be a link; example: https://hosted.weblate.org/projects/weblate/website/#information links to https://weblate.org/en-gb/contribute/ )
- [ ] Add screenshots to show where strings are being used. https://docs.weblate.org/en/latest/admin/translating.html#screenshots (seems really tedious! Can't we link to the website??)
- [ ] Mention you use Weblate for translations in the README

**Comment by swzCuroverse** [comment]
Define translation instructions to give translators a guideline. (can be a link; example: https://hosted.weblate.org/projects/weblate/website/#information links to https://weblate.org/en-gb/contribute/  --> looks done
https://hosted.weblate.org/projects/commonwl/#information

**Comment by mr-c** [comment]
> Define translation instructions to give translators a guideline. (can be a link; example: https://hosted.weblate.org/projects/weblate/website/#information links to https://weblate.org/en-gb/contribute/ --> looks done https://hosted.weblate.org/projects/commonwl/#information

See <https://hosted.weblate.org/projects/weblate/website/#information> ; it has a field "Instructions for translators" that contains the link <https://weblate.org/en-gb/contribute/>; That field doesn't show up at ours for lack of content.

**Comment by swzCuroverse** [comment]
@mr-c I can't edit that page because I don't have permission.  https://hosted.weblate.org/projects/commonwl/#information this already exists -- however, I can not edit.

**Comment by swzCuroverse** [comment]
Sounds good - will do.  I am running the auto-translate on the two languges and adding it as a suggestion.

**Comment by swzCuroverse** [comment]
oddly webplate doesn't have many instructions but -- "You can translate Weblate and many other projects at [hosted.weblate.org](https://hosted.weblate.org/engage/weblate/). which is just pointing ultimately back to the weblate translation page.

**Comment by swzCuroverse** [comment]
OK - I will write that today.

**Comment by mr-c** [comment]
Now that we are down to a single component, I put some simple instructions for translators and submitted the project with a cover letter.
