### ISSUE TITLE
License should use SPDX identifiers

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/user_guide#38]
https://spdx.org/licenses/

https://github.com/common-workflow-language/user_guide/edit/gh-pages/_extras/recommended-practices.md

**Comment by tobyhodges** [comment]
You mean, this is how an author should refer to a license within the metadata of a CWL file/description?

**Comment by mr-c** [comment]
Yes, previously we recommend using a URL to a copy of the license. Now we should recommend using an SPDX URI if available, falling back to the old advice for non-standard licenses.

**Comment by tobyhodges** [comment]
Ok, PR coming soon

**Comment by tobyhodges** [comment]
do you have an example of SPDX id usage to hand? I'd like to keep a link to an example if possible. No worries if you can't provide one easily - I will track one down

**Comment by tobyhodges** [comment]
or actually, I can't! Perhaps I can include an example instead of linking to one?

**Comment by mr-c** [comment]
`https://spdx.org/licenses/Apache-2.0` (leave off the `.html`)

**Comment by mr-c** [comment]
Formula is: short identifer from the list at https://spdx.org/licenses/  appended to `https://spdx.org/licenses/`

**Comment by tetron** [comment]
The recommend metadata should look like this:

```
$namespaces:
  s: http://schema.org/
  spdx: https://spdx.org/licenses/
s:license: spdx:Apache-2.0 
```

**Comment by mr-c** [comment]
@tetron Sure, though if we are only using a namespace once then we don't have to define the namespace

So for most CWL files that could be:

```
$namespaces:
  s: http://schema.org/
s:license: https://spdx.org/licenses/Apache-2.0 
# other s: declarations
```
