### ISSUE TITLE
Where can I download `interproscan.sh` on episode 19

### ISSUE THREAD

**Issue by manabuishii** [common-workflow-language/user_guide#48]
In episode 19

`interproscan.sh` is written inside `custom-types.cwl` .

But I can't find `interproscan.sh`.

Where can I download `interproscan.sh` ?

**Comment by mr-c** [comment]
Hello @manabuishii , you can find InterProScan at https://www.ebi.ac.uk/interpro/interproscan.html

**Comment by mr-c** [comment]
Or https://github.com/ebi-pf-team/interproscan/wiki/HowToDownload as found in the `doc` of that file.

It is a really big program (really a whole workflow + engine plus a lot of reference data) and we have yet to make a Docker container for it.

Hope this helped!

**Comment by manabuishii** [comment]
Thanks !!
