### ISSUE TITLE
[citation needed]

### ISSUE THREAD

**Issue by tobyhodges** [common-workflow-language/user_guide#8]
We need to add content to the CITATION file.

**Comment by tobyhodges** [comment]
@mr-c how would you like people to cite this user guide? I suppose that a formal citation isn't appropriate, but I suppose that we could get a DOI or something?

**Comment by mr-c** [comment]
Zenodo?

**Comment by tobyhodges** [comment]
ok. I've set Zenodo up to track this repo, so we can get a DOI through that when we create a release. Or, if you'd rather run that from your account, I'd be happy to yield responsibility?

**Comment by mr-c** [comment]
@tobyhodges Huzzah! Can we share the responsibility?

**Comment by tobyhodges** [comment]
Good question. I guess that it might have taken care of that automatically? If you log into Zenodo with your GH id, and look under Account -> GitHub, does it show this repo?

**Comment by mr-c** [comment]
It is listed, yep. When I cursor over the "off" switch I get a popup "This repository is being managed by another user of your GitHub organization"

**Comment by mr-c** [comment]
Shall I create an initial release to test it out?

**Comment by tobyhodges** [comment]
maybe merge that PR I just submitted first? But then yes!

**Comment by mr-c** [comment]
Done. I opened https://github.com/common-workflow-language/user_guide/pull/21 for you to add the DOI badge and citation info to

**Comment by tobyhodges** [comment]
sweet, thanks

**Comment by tobyhodges** [comment]
that should do it

**Comment by mr-c** [comment]
Hmm.. the title and contents leave a lot to be desired: https://zenodo.org/record/840130

Would also be nice to have the bibtex and the parent DOI itself in the citation page. 

While I want to give the Carpentry people credit for the template, it is a bit odd to see their names mixed in with ours.

@tobyhodges What options for customizing the release do we have?

**Comment by tobyhodges** [comment]
I've tried to update the title. Perhaps the contents can be added by adding "subjects"? I think that the difficulty here is that repos from GitHub are automatically set up as "Software" in Zenodo. I may be able to change that...

I'll add the bibtex shortly.

Looks like my options for authors is to reorder them or remove people entirely. If we choose the latter, I propose to add an acknowledgement of and link to the template repo in the "Additional Notes" field, which is currently empty. There is also a "Contributors section, which allows to name contributors, affiliation, and specify role (Contact person, editor, sponsor, data collector, etc...). I could try that out?

Generally, quite a lot of options for customisation. I will be more specific after a more thorough investigation.

**Comment by mr-c** [comment]
Looks like we can override using a `.zenodo.json`

@tobyhodges What's your ORCID?

```
{
    "description": "Common Workflow Language User Guide", 
    "license": "CC-BY-4.0", 
    "title": "Common Workflow Language User Guide", 
    "upload_type": "publication", 
    "publication_date": "2017-08-08", 
    "creators": [
        {
            "affiliation": "European Molecular Biology Laboratory", 
            "orcid": "",
            "name": "Toby Hodges"
        }, 
        {
            "affiliation": "Common Workflow Language project", 
            "orcid": "http://orcid.org/0000-0002-2961-9670",
            "name": "Michael R. Crusoe"
        }, 
    ], 
    "access_right": "open", 
    "related_identifiers": [
        {
            "scheme": "url", 
            "identifier": "https://github.com/common-workflow-language/user_guide/tree/v0.1", 
            "relation": "isSupplementTo"
        }, 
        {
            "scheme": "doi", 
            "identifier": "10.5281/zenodo.840129", 
            "relation": "isPartOf"
        }
    ]
}
```

**Comment by tobyhodges** [comment]
I never bothered with an ORCID after I decided to leave my research days behind me. Perhaps now I should actually get down to it.

**Comment by tobyhodges** [comment]
Do you think "Lesson" or "Publication" is the most appropriate type for the UG, instead of "Software"?

**Comment by mr-c** [comment]
@tobyhodges Yeah, I'm updating it as I work my way through http://developers.zenodo.org/#representation
